import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import VideoComponent from '@/components/VideoComponent';
import HTMLvsJSXTable from '@/components/HTMLvsJSXTable';
import HTMLArticle from '@/components/HTMLArticle';
import JSXArticle from '@/components/JSXArticle';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const embeddedCode = '<iframe width="560" height="315" src="https://www.youtube.com/embed/9GtB5G2xGTY" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>';
  const embeddedCode1 = '<iframe width="560" height="315" src="https://www.youtube.com/embed/Rh3tobg7hEo" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>';
  return (
    <>
      <Head>
        <title>JSX and HTML</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>src/pages/index.html</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Docs <span>-&gt;</span>
            </h2>
            <p>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Learn <span>-&gt;</span>
            </h2>
            <p>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Templates <span>-&gt;</span>
            </h2>
            <p>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Deploy <span>-&gt;</span>
            </h2>
            <p>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div>

        <hr style={{border: '3px solid white', width: '100%'}}/>
        <br />

      <HTMLArticle />

      <br />
      <br />

      <JSXArticle />

      <br />
      <br />

      <div className={styles.article}>
        <h2>HTML Vs. JSX</h2>
      </div>

      <br />
      <br />

      <HTMLvsJSXTable />

      <br />
      <br />

      <div className={styles.article}>
          <h3>
            Here is a video for a better understanding on JSX
          </h3>
          <br />
          <br />
      </div>

      <VideoComponent embeddedCode={embeddedCode} />

      <br />
      <br />

      <div className={styles.article}>
          <h3>
            Here is a sample project that uses JSX:
          </h3>
          <br />
          <br />
      </div>

      <VideoComponent embeddedCode={embeddedCode1} />

      </main>
    </>
  )
}
